steps:
- name: "gcr.io/cloud-builders/gcloud"
  args:
    - "app"
    - "deploy"
    - "/workspace/catalogue.py"  # Replace with the path to your app
  dir: "/workspace"  # This is the default working directory in Cloud Build
