steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  dir: "/workspace"  # This is the default working directory in Cloud Build
  substitutions:
    _INSTANCE_NAME: "myflix-p"
    _ZONE: "us-west4-b"
    _PROJECT_ID: "myflix"
