steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/pip'
    args: ['install', '-r', 'requirements.txt']

  # Step 2: Run tests (if applicable)
  # Note: Update this step based on your testing framework
  - name: 'gcr.io/cloud-builders/pip'
    args: ['install', 'pytest']
  - name: 'gcr.io/cloud-builders/pytest'
    args: ['tests/']

  # Step 3: Build and push a Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/myflix/catalogue-app', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/myflix/catalogue-app']

  # Step 4: SSH into the 'myflix' VM instance and restart the Docker container
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'myflix', '--zone', 'us-west4-b', '--command', 'docker pull gcr.io/$PROJECT_ID/catalogue-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'myflix', '--zone', 'us-west4-b', '--command', 'docker stop catalogue-app-container && docker rm catalogue-app-container']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'myflix', '--zone', 'us-west4-b', '--command', 'docker run -d -p 5000:5000 --name catalogue-app-container gcr.io/$PROJECT_ID/catalogue-app']
